irir_results_path: Results/Run_2026-03-24_16-28-32/Til inntektsrammeark.xlsx
LD_results_path: Results/Run_2026-01-27_09-44-24/Data_Resultater_LD.xlsx
RD_results_path: Results/Run_2026-01-27_09-44-24/Data_Resultater_RD.xlsx
data_resultater_ld_path: Results/Run_2026-03-24_16-28-32/Data_Resultater_LD.xlsx
data_resultater_rd_path: Results/Run_2026-03-24_16-28-32/Data_Resultater_RD.xlsx
forutsetninger:
  rho: 0.7
  referanserente: null
  finansparametere:
    gjeldsandel: 0.6
    noytral_realrente: 1.5
    ek-beta: 0.875
    markedspremie: 5.0
    skatt: 0.22
    inflasjon: 2.55
    swap: 3.98
    kredittpremie: 0.84
  omradepriser:
    NO1: 624.3
    NO2: 670.7
    NO3: 381.1
    NO4: 226.1
    NO5: 557.7
  kpi_justering:
    2024: 133.6
    2026: 140.6
  aarslonn:
    2024: 129.9
    2026: 141.7
kalibrering:
  sum_ir_k_per_sum_akg_pct: -0.023
  sum_renter_avvik_per_sum_akg_pct: -0.098
dea_overrides:
  ld:
    753: null
    121: 0.81
    167: 0.52
    222: 1.07
    294: 0.74
    743: 0.87
    852: 0.91
    873: 0.85
  rd:
    32: 0.82
    43: 0.74
    63: 0.98
    88: 0.94
    91: 0.96
    98: 1.2
    157: 2.23
    161: 1.17
    162: 0.95
    213: 1.04
    222: 1.14
    267: 1.03
    274: 0.85
    349: 0.95
    447: 0.75
    542: 1.98
    599: 1.17
    685: 1.0
    35: null
    42: null
    116: null
    135: null
    223: null
kundetillegg_path: Data/kundetillegg.csv
prognose:
  selskap_id: 7
  forutsetninger:
    referanserente_per_year:
      2026: 10.5
      2027: 9.7
      2028: 10.45
      2029: 10.05
      2030: 10.35
      2031: 10.0
    kraftpris_per_year:
      2026: 500.0
      2027: 490.0
      2028: 480.0
      2029: 475.0
      2030: 470.0
      2031: 465.0
    inflasjon_per_year:
      2026: 2.55
      2027: 2.5
      2028: 3.0
      2029: 3.5
      2030: 4.0
      2031: 4.5
  fusjon:
    enabled: true
    fusjonsaar: 2030
    omstillingskostnad_fast_kkr: 1000.0
    omstillingskostnad_variabel_pst: 5.0
  synergi:
    enabled: true
    kostnadsreduksjon_pst: 10.5
    synergistart_aar: 2027
    full_synergi_aar: 2029
    synergiperiode_slutt: 2031
  investeringer:
    avskrivningssats_pst: 4.0
    nyinvesteringer_per_year:
      2026: 0
      2027: 0
      2028: 0
      2029: 0
      2030: 0
      2031: 0
    reinvesteringer_per_year:
      2026: 0
      2027: 0
      2028: 0
      2029: 0
      2030: 0
      2031: 0
    kundeinvesteringer_per_year:
      2026: 0
      2027: 0
      2028: 0
      2029: 0
      2030: 0
      2031: 0
  om_justering_pst: 0.0
  rho: 0.7
